# Setting up the Notebook

In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
# import recommendation engines from external .py file
from property_recommendation import FEATURES_FOR_DISPLAY, FEATURES_WITH_LISTING_ID, PairwiseItemRecEngine, UserItemRecEngine

## Load the Data

In [4]:
items = pd.read_csv("df_task2_onehot.csv")
items.head()

,listing_id,title,address,property_name,property_type,tenure,built_year,num_beds,num_baths,size_sqft,...,property_type_landed,property_type_semi_detached_house,property_type_shophouse,property_type_terraced_house,property_type_townhouse,property_type_walk_up,tenure_nan,tenure_freehold,tenure_99-110_year,tenure_999+year
0,122881,hdb flat for sale in 866 yishun street 81,sembawang / yishun (d27),866 yishun street 81,hdb,NaN,1988,3,2,1115,...,0,0,0,0,0,0,1,0,0,0
1,259374,hdb flat for sale in 506b serangoon north aven...,hougang / punggol / sengkang (d19),hdb-serangoon estate,hdb,99-year leasehold,1992,4,2,1575,...,0,0,0,0,0,0,0,1,0,0
2,665422,4 bed condo for sale in meyerhouse,128 meyer road,meyerhouse,condo,freehold,2022,4,6,3070,...,0,0,0,0,0,0,0,0,0,1
3,857699,3 bed condo for sale in leedon green,26 leedon heights,leedon green,condo,freehold,2023,3,2,958,...,0,0,0,0,0,0,0,0,0,1
4,216061,2 bed condo for sale in one bernam,1 bernam street,one bernam,condo,99-year leasehold,2026,2,1,732,...,0,0,0,0,0,0,0,1,0,0

In [5]:
user_profiles = pd.read_csv("user_profile.csv")
user_profiles.head()

,profile_id,listing_id,view_time,index,num_beds,price,property_type,planning_area,subzone,name_of_nearest_mrt,num_baths,tenure,built_year,size_sqft,per_price
0,0,243265,4,0,"6.0,7.0,5.0,4.0,8.0",NaN,"condo,hdb",NaN,NaN,NaN,NaN,NaN,"1990,2029.0","0,2105","1646,9547"
1,0,844619,2,0,"6.0,7.0,5.0,4.0,8.0",NaN,"condo,hdb",NaN,NaN,NaN,NaN,NaN,"1990,2029.0","0,2105","1646,9547"
2,0,887175,5,0,"6.0,7.0,5.0,4.0,8.0",NaN,"condo,hdb",NaN,NaN,NaN,NaN,NaN,"1990,2029.0","0,2105","1646,9547"
3,0,761559,2,0,"6.0,7.0,5.0,4.0,8.0",NaN,"condo,hdb",NaN,NaN,NaN,NaN,NaN,"1990,2029.0","0,2105","1646,9547"
4,0,211308,2,0,"6.0,7.0,5.0,4.0,8.0",NaN,"condo,hdb",NaN,NaN,NaN,NaN,NaN,"1990,2029.0","0,2105","1646,9547"

# Computing the Top Recommendations

## Scenario 1: Recommend based on the item last viewed/currently being viewed

In [6]:
k = 3
pairwiseItemRecEngine = PairwiseItemRecEngine(items)
get_top_recommendations = pairwiseItemRecEngine.get_top_recommendations

In [7]:
for profile_id in range(5): # adjust to see more examples
    print("======================================== user {} ========================================".format(profile_id))
    
    # last viewed/currently viewed listing id
    reference_item_index = user_profiles[user_profiles['profile_id'] == profile_id]['view_time'].idxmax()
    view_history = user_profiles.iloc[[reference_item_index]]
    reference_lids = view_history['listing_id'].tolist()
    print("reference_item:")
    print(items[items['listing_id'].isin(reference_lids)][FEATURES_FOR_DISPLAY])
    
    # recommended listing ids
    most_similar_lids = get_top_recommendations(view_history, k)
    print("recommendations:")
    print(items[items['listing_id'].isin(most_similar_lids)][FEATURES_FOR_DISPLAY])

======================================== user 0 ========================================
reference_item:
       listing_id property_type  num_beds  num_baths       lat         lng  \
16019      524387         condo         4          4  1.317717  103.829904

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
16019       2077                                      1  6300000        2014

         tenure
16019  freehold
recommendations:
       listing_id property_type  num_beds  num_baths       lat         lng  \
9704       184136         condo         4          4  1.311239  103.828154
15433      660576         condo         4          4  1.317717  103.829904
19380      851641         condo         3          2  1.340464  103.883733

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
9704        2476                                      1  7875000        2014
15433       2077                                      1  6300000        2014
19380        947                                      2  1933000        2026

                  tenure
9704            freehold
15433           freehold
19380  99-year leasehold
======================================== user 1 ========================================
reference_item:
      listing_id property_type  num_beds  num_baths       lat         lng  \
2111      675624     apartment         5          3  1.316487  103.857467

      size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
2111       1507                                      0  3192000        2023

        tenure
2111  freehold
recommendations:
      listing_id    property_type  num_beds  num_baths       lat         lng  \
983       453768        apartment         5          3  1.316487  103.857467
6297      871563              hdb         3          2  1.387752  103.769418
8832      410080  executive condo         4          3  1.433393  103.843016

      size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
983        1507                                      0  3193000        2023
6297       1119                                      3   491400        1988
8832       1313                                      6  1701000        2015

                 tenure
983            freehold
6297                NaN
8832  99-year leasehold
======================================== user 2 ========================================
reference_item:
      listing_id property_type  num_beds  num_baths       lat         lng  \
7136      523248         condo         1          1  1.328903  103.869411

      size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
7136        753                                      1  1365500        2017

                 tenure
7136  99-year leasehold
recommendations:
       listing_id property_type  num_beds  num_baths       lat         lng  \
2310       275988         condo         1          1  1.328848  103.869039
4204       879499         condo         1          1  1.328848  103.869039
15276      619766           hdb         2          2  1.351073  103.746173

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
2310         753                                      1  1365500        2017
4204         753                                      1  1365000        2017
15276        786                                      0   419000        1984

                  tenure
2310   99-year leasehold
4204   99-year leasehold
15276  99-year leasehold
======================================== user 3 ========================================
reference_item:
      listing_id property_type  num_beds  num_baths       lat         lng  \
4488      601785         condo         4          3  1.312942  103.841552

      size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
4488       1496                                      0  4440900        2020

        tenure
4488  freehold
recommendations:
       listing_id property_type  num_beds  num_baths       lat         lng  \
13129      794688           hdb         2          1  1.331617  103.931237
17805      203146     apartment         3          4  1.305146  103.826053
19364      726920         condo         3          2  1.308766  103.809065

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
13129        635                                      2   372800        1978
17805       1507                                      2  4620000        2008
19364        850                                      1  2230100        2024

                   tenure
13129   99-year leasehold
17805  999-year leasehold
19364            freehold
======================================== user 4 ========================================
reference_item:
      listing_id property_type  num_beds  num_baths       lat         lng  \
7198      305042         condo         4          3  1.383033  103.892065

      size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
7198       1324                                      0  2079000        2023

                 tenure
7198  99-year leasehold
recommendations:
      listing_id property_type  num_beds  num_baths       lat         lng  \
371       664945         condo         4          3  1.383033  103.892065
3719      152766         condo         4          3  1.383033  103.892065
4704      396631         condo         4          3  1.383033  103.892065

      size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
371        1324                                      0  2475900        2023
3719       1324                                      0  2532000        2023
4704       1324                                      0  2659600        2023

                 tenure
371   99-year leasehold
3719  99-year leasehold
4704  99-year leasehold

## Scenario 2: Recommend based on view history
### Approach 1: Pairwise item-item similarity 
with filtering based on search criteria

In [8]:
k = 3
pairwiseItemRecEngine = PairwiseItemRecEngine(items)
get_top_recommendations = pairwiseItemRecEngine.get_top_recommendations_based_on_view_history

In [9]:
for profile_id in range(5): # adjust to see more examples
    print("======================================== user {} ========================================".format(profile_id))
    
    # last 15 viewed listing ids
    view_history = user_profiles[user_profiles['profile_id'] == profile_id]
    reference_lids = view_history['listing_id'].to_list()
    print("view history:")
    print(items[items['listing_id'].isin(reference_lids)][FEATURES_FOR_DISPLAY])
    
    # recommended listing ids
    most_similar_lids = pairwiseItemRecEngine.get_top_recommendations_based_on_view_history(view_history, k)
    print("recommendations:")
    print(items[items['listing_id'].isin(most_similar_lids)][FEATURES_FOR_DISPLAY])

======================================== user 0 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
250        802295         condo         4          3  1.313186  103.899693
4295       211308         condo         4          4  1.298416  103.857178
4618       844619         condo         4          3  1.330709  103.868391
5991       593601         condo         4          4  1.344334  103.878690
6573       243265         condo         4          3  1.314664  103.831084
7457       397248         condo         4          4  1.283016  103.839887
7991       182886         condo         5          6  1.312402  103.841172
9239       350347         condo         4          3  1.312364  103.803271
10079      867420         condo         4          4  1.312076  103.804055
12686      190211         condo         4          3  1.310184  103.835914
13103      761559         condo         4          4  1.294106  103.836735
14440      777580         condo         5          5  1.317138  103.759701
16019      524387         condo         4          4  1.317717  103.829904
16553      967997         condo         4          3  1.330403  103.794939
19516      887175         condo         5          4  1.369097  103.833145

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
250         1227                                      1  2605300        2025
4295        1808                                      0  5094600        2024
4618        1324                                      1  3347400        2024
5991        1216                                      1  2598800        2022
6573        1572                                      1  4989600        2022
7457        1399                                      0  3465000        2023
7991        1819                                      0  4300800        2023
9239        1496                                      1  4894000        2023
10079       1270                                      1  3681300        2023
12686       2056                                      0  7560000        2025
13103       2056                                      1  7106400        2025
14440       1991                                      2  3444000        2023
16019       2077                                      1  6300000        2014
16553       1259                                      2  3878700        2021
19516       1475                                      0  3255000        2026

                  tenure
250             freehold
4295   99-year leasehold
4618            freehold
5991            freehold
6573            freehold
7457   99-year leasehold
7991   99-year leasehold
9239            freehold
10079           freehold
12686           freehold
13103           freehold
14440  99-year leasehold
16019           freehold
16553           freehold
19516  99-year leasehold
recommendations:
       listing_id        property_type  num_beds  num_baths       lat  \
2920       573907                condo         3          3  1.312364
7702       192538                condo         3          2  1.330709
11238      797503  semi-detached house         5          5  1.330792

              lng  size_sqft  dist_to_nearest_important_mrt_rounded    price  \
2920   103.803271       1044                                      1  3279200
7702   103.868391        872                                      1  2551500
11238  103.757727       5390                                      2  6457500

       built_year    tenure
2920         2023  freehold
7702         2024  freehold
11238        2013  freehold
======================================== user 1 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
985        504839         condo         5          4  1.369097  103.833145
2111       675624     apartment         5          3  1.316487  103.857467
2446       742039         condo         5          5  1.298416  103.857178
5591       667893         condo         5          3  1.312402  103.841172
7034       336888         condo         5          4  1.339338  103.763893
9133       866887         condo         5          5  1.317138  103.759701
9174       141036         condo         5          5  1.369097  103.833145
9218       337545         condo         5          4  1.311323  103.852476
9350       950151         condo         5          4  1.300581  103.899394
9650       477545         condo         5          5  1.311323  103.852476
13012      588014         condo         5          3  1.369097  103.833145
13075      364468         condo         5          4  1.440028  103.827741
16848      544542         condo         5          7  1.298416  103.857178
17102      286937         condo         5          5  1.317138  103.759701
17587      495208         condo         5          2  1.369097  103.833145

       size_sqft  dist_to_nearest_important_mrt_rounded     price  built_year  \
985         1475                                      0   3329600        2026
2111        1507                                      0   3192000        2023
2446        3616                                      0  16275000        2024
5591        1819                                      0   4171600        2023
7034        1884                                      2   4438400        2024
9133        1711                                      2   3297000        2023
9174        2293                                      0   5880000        2026
9218        1582                                      0   3150200        2026
9350        2142                                      2   5334000        2024
9650        1679                                      0   3347400        2026
13012       1475                                      0   2310000        2026
13075       1528                                      4   1890000        2026
16848       3617                                      0  15624000        2024
17102       1711                                      2   3213000        2023
17587       1475                                      0   3329600        2026

                  tenure
985    99-year leasehold
2111            freehold
2446   99-year leasehold
5591   99-year leasehold
7034            freehold
9133   99-year leasehold
9174   99-year leasehold
9218   99-year leasehold
9350            freehold
9650   99-year leasehold
13012  99-year leasehold
13075  99-year leasehold
16848  99-year leasehold
17102  99-year leasehold
17587  99-year leasehold
recommendations:
       listing_id   property_type  num_beds  num_baths       lat         lng  \
11022      905543           condo         2          2  1.305832  103.838259
14447      100901  terraced house         5          3  1.318344  103.948369
18930      149379             hdb         3          2  1.276669  103.810766

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
11022        775                                      1  2326800        2023
14447       2926                                      1  2520000        1996
18930       1001                                      1   953400        2017

                  tenure
11022           freehold
14447  99-year leasehold
18930  99-year leasehold
======================================== user 2 ========================================
view history:
       listing_id    property_type  num_beds  num_baths       lat         lng  \
783        865700            condo         4          3  1.319516  103.880974
1057       886510            condo         2          2  1.312076  103.804055
1239       339405            condo         4          4  1.300416  103.861679
5489       376545            condo         2          2  1.302770  103.869435
7136       523248            condo         1          1  1.328903  103.869411
7632       857585  executive condo         4          3  1.432006  103.800800
7783       944835            condo         4          3  1.300581  103.899394
8453       350832            condo         2          2  1.321588  103.864694
8457       575303            condo         2          1  1.377286  103.756863
9363       372096            condo         4          3  1.340464  103.883733
9552       794786            condo         2          2  1.340464  103.883733
10404      860881  executive condo         3          2  1.434928  103.845282
11259      161123            condo         4          6  1.294106  103.836735
15953      499167            condo         3          3  1.309169  103.837555
17398      223842            condo         3          3  1.301419  103.848644

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
783         1206                                      1  2100000        2017
1057         732                                      1  2071600        2023
1239        2174                                      1  5821500        2013
5489         818                                      1  2528400        2023
7136         753                                      1  1365500        2017
7632        1249                                      1  1469800        2017
7783        1302                                      2  3219300        2024
8453         700                                      0  1260000        2016
8457         657                                      2   984900        2025
9363        1356                                      2  2257500        2026
9552         732                                      2  1467900        2026
10404       1001                                      6  1246200        2027
11259       2056                                      1  7387800        2025
15953       2142                                      0  4725000        2011
17398       2009                                      0  3675000        2014

                  tenure
783    99-year leasehold
1057            freehold
1239   99-year leasehold
5489   99-year leasehold
7136   99-year leasehold
7632   99-year leasehold
7783            freehold
8453   99-year leasehold
8457   99-year leasehold
9363   99-year leasehold
9552   99-year leasehold
10404  99-year leasehold
11259           freehold
15953           freehold
17398           freehold
recommendations:
       listing_id property_type  num_beds  num_baths       lat         lng  \
5634       185317         condo         3          2  1.286177  103.839550
8292       702681         condo         1          1  1.298416  103.857178
11439      204049         condo         3          3  1.310429  103.802821

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
5634        1076                                      1  2205000        2025
8292         409                                      0  1561400        2024
11439       1055                                      1  2955600        2025

                  tenure
5634   99-year leasehold
8292   99-year leasehold
11439           freehold
======================================== user 3 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
588        237551         condo         4          4  1.315961  103.836848
821        297697         condo         5          5  1.312402  103.841172
1252       926734         condo         3          2  1.315475  103.841113
1542       382872         condo         4          4  1.312942  103.841552
4488       601785         condo         4          3  1.312942  103.841552
6573       243265         condo         4          3  1.314664  103.831084
7182       200180         condo         3          3  1.313524  103.841908
7851       120602         condo         3          3  1.352056  103.758479
11663      934362         condo         3          3  1.315795  103.832096
13309      814081         condo         3          3  1.312402  103.841172
15857      627497         condo         3          2  1.310184  103.835914
16387      536802         condo         4          3  1.310184  103.835914
17600      659319         condo         3          3  1.315961  103.836848
19043      764877         condo         3          3  1.315961  103.836848
19248      612897         condo         5          4  1.312402  103.841172

       size_sqft  dist_to_nearest_important_mrt_rounded     price  built_year  \
588         1378                                      0   4406800        2023
821         1819                                      0   4278800        2023
1252        1001                                      0   2832900        2026
1542        1496                                      0   4410000        2020
4488        1496                                      0   4440900        2020
6573        1572                                      1   4989600        2022
7182        2164                                      0   4084500        2013
7851        1109                                      1   1449000        2005
11663       1249                                      1   3906000        2022
13309       1055                                      0   2577800        2023
15857        893                                      0   3360000        2025
16387       2368                                      0  10290000        2025
17600       1163                                      0   3386200        2023
19043       1163                                      0   3386200        2023
19248       1819                                      0   4278800        2023

                  tenure
588             freehold
821    99-year leasehold
1252            freehold
1542            freehold
4488            freehold
6573            freehold
7182   99-year leasehold
7851   99-year leasehold
11663           freehold
13309  99-year leasehold
15857           freehold
16387           freehold
17600           freehold
19043           freehold
19248  99-year leasehold
recommendations:
       listing_id property_type  num_beds  num_baths       lat         lng  \
1627       827790         condo         4          3  1.354977  103.967403
5307       558835         condo         2          2  1.427571  103.785752
16794      643793           hdb         2          2  1.441411  103.778486

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
1627        1539                                      2  2068500        2014
5307        1269                                      1  1155000        2014
16794        721                                      1   451500        2013

                  tenure
1627   99-year leasehold
5307   99-year leasehold
16794  99-year leasehold
======================================== user 4 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
4948       682504         condo         4          2  1.308696  103.898132
5298       450511         condo         3          2  1.308696  103.898132
5811       425951         condo         3          2  1.308696  103.898132
6133       496786         condo         4          3  1.300581  103.899394
7198       305042         condo         4          3  1.383033  103.892065
7604       901635         condo         3          3  1.306702  103.888771
9694       618049         condo         3          2  1.308696  103.898132
11633      275538         condo         4          3  1.300581  103.899394
12259      110976         condo         4          2  1.300581  103.899394
13217      963960         condo         4          3  1.434928  103.845282
14620      990387         condo         4          3  1.300581  103.899394
15438      336144         condo         4          3  1.300581  103.899394
15876      370936         condo         4          3  1.300581  103.899394
16023      472916         condo         3          2  1.300581  103.899394
16940      217530         condo         4          3  1.383033  103.892065

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
4948        1163                                      1  2422600        2025
5298         915                                      1  2068500        2025
5811         797                                      1  1827000        2025
6133        1302                                      2  3299100        2024
7198        1324                                      0  2079000        2023
7604        1528                                      1  2520000        2013
9694         797                                      1  1837500        2025
11633       1582                                      2  3851400        2024
12259       1572                                      2  4040400        2024
13217       1302                                      6  1396500        2027
14620       1302                                      2  3299100        2024
15438       1572                                      2  3655400        2024
15876       1302                                      2  3255000        2024
16023        947                                      2  2289000        2024
16940       1324                                      0  2659600        2023

                  tenure
4948            freehold
5298            freehold
5811            freehold
6133            freehold
7198   99-year leasehold
7604   99-year leasehold
9694            freehold
11633           freehold
12259           freehold
13217  99-year leasehold
14620           freehold
15438           freehold
15876           freehold
16023           freehold
16940  99-year leasehold
recommendations:
       listing_id    property_type  num_beds  num_baths       lat         lng  \
8858       536624            condo         2          2  1.291420  103.844268
18460      618506  executive condo         4          3  1.417017  103.845035
19448      272193        apartment         2          2  1.303839  103.861482

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
8858         484                                      0  1711500        2026
18460       1184                                      5  1520400        2017
19448        883                                      1  1037400        1977

                  tenure
8858   99-year leasehold
18460  99-year leasehold
19448  99-year leasehold

### Approach 2: User-item similarity 
with filtering based on search criteria

In [10]:
k = 3
userItemRecEngine = UserItemRecEngine(items)
get_top_recommendations = userItemRecEngine.get_top_recommendations_based_on_view_history

In [11]:
for profile_id in range(5): # adjust to see more examples
    print("======================================== user {} ========================================".format(profile_id))
    
    # last 15 viewed listing ids
    userItemRecEngine = UserItemRecEngine(items)
    view_history = user_profiles[user_profiles['profile_id'] == profile_id]
    reference_lids = view_history['listing_id'].to_list()
    print("view history:")
    print(items[items['listing_id'].isin(reference_lids)][FEATURES_FOR_DISPLAY])

    most_similar_lids = userItemRecEngine.get_top_recommendations_based_on_view_history(view_history, k)
    print("recommendations:")
    print(items[items['listing_id'].isin(most_similar_lids)][FEATURES_FOR_DISPLAY])

======================================== user 0 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
250        802295         condo         4          3  1.313186  103.899693
4295       211308         condo         4          4  1.298416  103.857178
4618       844619         condo         4          3  1.330709  103.868391
5991       593601         condo         4          4  1.344334  103.878690
6573       243265         condo         4          3  1.314664  103.831084
7457       397248         condo         4          4  1.283016  103.839887
7991       182886         condo         5          6  1.312402  103.841172
9239       350347         condo         4          3  1.312364  103.803271
10079      867420         condo         4          4  1.312076  103.804055
12686      190211         condo         4          3  1.310184  103.835914
13103      761559         condo         4          4  1.294106  103.836735
14440      777580         condo         5          5  1.317138  103.759701
16019      524387         condo         4          4  1.317717  103.829904
16553      967997         condo         4          3  1.330403  103.794939
19516      887175         condo         5          4  1.369097  103.833145

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
250         1227                                      1  2605300        2025
4295        1808                                      0  5094600        2024
4618        1324                                      1  3347400        2024
5991        1216                                      1  2598800        2022
6573        1572                                      1  4989600        2022
7457        1399                                      0  3465000        2023
7991        1819                                      0  4300800        2023
9239        1496                                      1  4894000        2023
10079       1270                                      1  3681300        2023
12686       2056                                      0  7560000        2025
13103       2056                                      1  7106400        2025
14440       1991                                      2  3444000        2023
16019       2077                                      1  6300000        2014
16553       1259                                      2  3878700        2021
19516       1475                                      0  3255000        2026

                  tenure
250             freehold
4295   99-year leasehold
4618            freehold
5991            freehold
6573            freehold
7457   99-year leasehold
7991   99-year leasehold
9239            freehold
10079           freehold
12686           freehold
13103           freehold
14440  99-year leasehold
16019           freehold
16553           freehold
19516  99-year leasehold
recommendations:
       listing_id        property_type  num_beds  num_baths       lat  \
2920       573907                condo         3          3  1.312364
7702       192538                condo         3          2  1.330709
11238      797503  semi-detached house         5          5  1.330792

              lng  size_sqft  dist_to_nearest_important_mrt_rounded    price  \
2920   103.803271       1044                                      1  3279200
7702   103.868391        872                                      1  2551500
11238  103.757727       5390                                      2  6457500

       built_year    tenure
2920         2023  freehold
7702         2024  freehold
11238        2013  freehold
======================================== user 1 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
985        504839         condo         5          4  1.369097  103.833145
2111       675624     apartment         5          3  1.316487  103.857467
2446       742039         condo         5          5  1.298416  103.857178
5591       667893         condo         5          3  1.312402  103.841172
7034       336888         condo         5          4  1.339338  103.763893
9133       866887         condo         5          5  1.317138  103.759701
9174       141036         condo         5          5  1.369097  103.833145
9218       337545         condo         5          4  1.311323  103.852476
9350       950151         condo         5          4  1.300581  103.899394
9650       477545         condo         5          5  1.311323  103.852476
13012      588014         condo         5          3  1.369097  103.833145
13075      364468         condo         5          4  1.440028  103.827741
16848      544542         condo         5          7  1.298416  103.857178
17102      286937         condo         5          5  1.317138  103.759701
17587      495208         condo         5          2  1.369097  103.833145

       size_sqft  dist_to_nearest_important_mrt_rounded     price  built_year  \
985         1475                                      0   3329600        2026
2111        1507                                      0   3192000        2023
2446        3616                                      0  16275000        2024
5591        1819                                      0   4171600        2023
7034        1884                                      2   4438400        2024
9133        1711                                      2   3297000        2023
9174        2293                                      0   5880000        2026
9218        1582                                      0   3150200        2026
9350        2142                                      2   5334000        2024
9650        1679                                      0   3347400        2026
13012       1475                                      0   2310000        2026
13075       1528                                      4   1890000        2026
16848       3617                                      0  15624000        2024
17102       1711                                      2   3213000        2023
17587       1475                                      0   3329600        2026

                  tenure
985    99-year leasehold
2111            freehold
2446   99-year leasehold
5591   99-year leasehold
7034            freehold
9133   99-year leasehold
9174   99-year leasehold
9218   99-year leasehold
9350            freehold
9650   99-year leasehold
13012  99-year leasehold
13075  99-year leasehold
16848  99-year leasehold
17102  99-year leasehold
17587  99-year leasehold
recommendations:
       listing_id   property_type  num_beds  num_baths       lat         lng  \
11022      905543           condo         2          2  1.305832  103.838259
14447      100901  terraced house         5          3  1.318344  103.948369
18930      149379             hdb         3          2  1.276669  103.810766

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
11022        775                                      1  2326800        2023
14447       2926                                      1  2520000        1996
18930       1001                                      1   953400        2017

                  tenure
11022           freehold
14447  99-year leasehold
18930  99-year leasehold
======================================== user 2 ========================================
view history:
       listing_id    property_type  num_beds  num_baths       lat         lng  \
783        865700            condo         4          3  1.319516  103.880974
1057       886510            condo         2          2  1.312076  103.804055
1239       339405            condo         4          4  1.300416  103.861679
5489       376545            condo         2          2  1.302770  103.869435
7136       523248            condo         1          1  1.328903  103.869411
7632       857585  executive condo         4          3  1.432006  103.800800
7783       944835            condo         4          3  1.300581  103.899394
8453       350832            condo         2          2  1.321588  103.864694
8457       575303            condo         2          1  1.377286  103.756863
9363       372096            condo         4          3  1.340464  103.883733
9552       794786            condo         2          2  1.340464  103.883733
10404      860881  executive condo         3          2  1.434928  103.845282
11259      161123            condo         4          6  1.294106  103.836735
15953      499167            condo         3          3  1.309169  103.837555
17398      223842            condo         3          3  1.301419  103.848644

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
783         1206                                      1  2100000        2017
1057         732                                      1  2071600        2023
1239        2174                                      1  5821500        2013
5489         818                                      1  2528400        2023
7136         753                                      1  1365500        2017
7632        1249                                      1  1469800        2017
7783        1302                                      2  3219300        2024
8453         700                                      0  1260000        2016
8457         657                                      2   984900        2025
9363        1356                                      2  2257500        2026
9552         732                                      2  1467900        2026
10404       1001                                      6  1246200        2027
11259       2056                                      1  7387800        2025
15953       2142                                      0  4725000        2011
17398       2009                                      0  3675000        2014

                  tenure
783    99-year leasehold
1057            freehold
1239   99-year leasehold
5489   99-year leasehold
7136   99-year leasehold
7632   99-year leasehold
7783            freehold
8453   99-year leasehold
8457   99-year leasehold
9363   99-year leasehold
9552   99-year leasehold
10404  99-year leasehold
11259           freehold
15953           freehold
17398           freehold

C:\Users\linfa\Academics\year-1-sem-1\knowledge-discovery-and-data-mining\project\property_recommendation.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  view_history['view_score'] = view_history['view_time']/last_view_time
C:\Users\linfa\Academics\year-1-sem-1\knowledge-discovery-and-data-mining\project\property_recommendation.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  view_history['view_score'] = view_history['view_time']/last_view_time
C:\Users\linfa\Academics\year-1-sem-1\knowledge-discovery-and-data-mining\project\property_recommendation.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  view_history['view_score'] = view_history['view_time']/last_view_time

recommendations:
       listing_id property_type  num_beds  num_baths       lat         lng  \
5634       185317         condo         3          2  1.286177  103.839550
8292       702681         condo         1          1  1.298416  103.857178
11439      204049         condo         3          3  1.310429  103.802821

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
5634        1076                                      1  2205000        2025
8292         409                                      0  1561400        2024
11439       1055                                      1  2955600        2025

                  tenure
5634   99-year leasehold
8292   99-year leasehold
11439           freehold
======================================== user 3 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
588        237551         condo         4          4  1.315961  103.836848
821        297697         condo         5          5  1.312402  103.841172
1252       926734         condo         3          2  1.315475  103.841113
1542       382872         condo         4          4  1.312942  103.841552
4488       601785         condo         4          3  1.312942  103.841552
6573       243265         condo         4          3  1.314664  103.831084
7182       200180         condo         3          3  1.313524  103.841908
7851       120602         condo         3          3  1.352056  103.758479
11663      934362         condo         3          3  1.315795  103.832096
13309      814081         condo         3          3  1.312402  103.841172
15857      627497         condo         3          2  1.310184  103.835914
16387      536802         condo         4          3  1.310184  103.835914
17600      659319         condo         3          3  1.315961  103.836848
19043      764877         condo         3          3  1.315961  103.836848
19248      612897         condo         5          4  1.312402  103.841172

       size_sqft  dist_to_nearest_important_mrt_rounded     price  built_year  \
588         1378                                      0   4406800        2023
821         1819                                      0   4278800        2023
1252        1001                                      0   2832900        2026
1542        1496                                      0   4410000        2020
4488        1496                                      0   4440900        2020
6573        1572                                      1   4989600        2022
7182        2164                                      0   4084500        2013
7851        1109                                      1   1449000        2005
11663       1249                                      1   3906000        2022
13309       1055                                      0   2577800        2023
15857        893                                      0   3360000        2025
16387       2368                                      0  10290000        2025
17600       1163                                      0   3386200        2023
19043       1163                                      0   3386200        2023
19248       1819                                      0   4278800        2023

                  tenure
588             freehold
821    99-year leasehold
1252            freehold
1542            freehold
4488            freehold
6573            freehold
7182   99-year leasehold
7851   99-year leasehold
11663           freehold
13309  99-year leasehold
15857           freehold
16387           freehold
17600           freehold
19043           freehold
19248  99-year leasehold
recommendations:
       listing_id property_type  num_beds  num_baths       lat         lng  \
1150       317046           hdb         3          2  1.378496  103.766708
1627       827790         condo         4          3  1.354977  103.967403
12641      562959         condo         3          3  1.311628  103.793886

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
1150        1313                                      3   618400        1998
1627        1539                                      2  2068500        2014
12641       1281                                      0  4271100        2025

                  tenure
1150                 NaN
1627   99-year leasehold
12641  99-year leasehold
======================================== user 4 ========================================
view history:
       listing_id property_type  num_beds  num_baths       lat         lng  \
4948       682504         condo         4          2  1.308696  103.898132
5298       450511         condo         3          2  1.308696  103.898132
5811       425951         condo         3          2  1.308696  103.898132
6133       496786         condo         4          3  1.300581  103.899394
7198       305042         condo         4          3  1.383033  103.892065
7604       901635         condo         3          3  1.306702  103.888771
9694       618049         condo         3          2  1.308696  103.898132
11633      275538         condo         4          3  1.300581  103.899394
12259      110976         condo         4          2  1.300581  103.899394
13217      963960         condo         4          3  1.434928  103.845282
14620      990387         condo         4          3  1.300581  103.899394
15438      336144         condo         4          3  1.300581  103.899394
15876      370936         condo         4          3  1.300581  103.899394
16023      472916         condo         3          2  1.300581  103.899394
16940      217530         condo         4          3  1.383033  103.892065

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
4948        1163                                      1  2422600        2025
5298         915                                      1  2068500        2025
5811         797                                      1  1827000        2025
6133        1302                                      2  3299100        2024
7198        1324                                      0  2079000        2023
7604        1528                                      1  2520000        2013
9694         797                                      1  1837500        2025
11633       1582                                      2  3851400        2024
12259       1572                                      2  4040400        2024
13217       1302                                      6  1396500        2027
14620       1302                                      2  3299100        2024
15438       1572                                      2  3655400        2024
15876       1302                                      2  3255000        2024
16023        947                                      2  2289000        2024
16940       1324                                      0  2659600        2023

                  tenure
4948            freehold
5298            freehold
5811            freehold
6133            freehold
7198   99-year leasehold
7604   99-year leasehold
9694            freehold
11633           freehold
12259           freehold
13217  99-year leasehold
14620           freehold
15438           freehold
15876           freehold
16023           freehold
16940  99-year leasehold
recommendations:
       listing_id    property_type  num_beds  num_baths       lat         lng  \
8858       536624            condo         2          2  1.291420  103.844268
9759       905005              hdb         3          2  1.401519  103.914497
18460      618506  executive condo         4          3  1.417017  103.845035

       size_sqft  dist_to_nearest_important_mrt_rounded    price  built_year  \
8858         484                                      0  1711500        2026
9759        1001                                      2   651000        2016
18460       1184                                      5  1520400        2017

                  tenure
8858   99-year leasehold
9759   99-year leasehold
18460  99-year leasehold

C:\Users\linfa\Academics\year-1-sem-1\knowledge-discovery-and-data-mining\project\property_recommendation.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  view_history['view_score'] = view_history['view_time']/last_view_time
C:\Users\linfa\Academics\year-1-sem-1\knowledge-discovery-and-data-mining\project\property_recommendation.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  view_history['view_score'] = view_history['view_time']/last_view_time